import { useEffect, useState } from 'react'
import { FiAlertTriangle, FiCheckCircle, FiFolder, FiShield } from 'react-icons/fi'
import Button from '../../components/Buttons/Button.jsx'
import StatCard from '../../components/Cards/StatCard.jsx'
import BugTable from '../../components/Tables/BugTable.jsx'
import { useAuth } from '../../hooks/useAuth.js'
import api from '../../services/api.js'

const icons = [FiShield, FiAlertTriangle, FiCheckCircle, FiFolder]
export default function Dashboard() {
  const [data, setData] = useState(null); const { user } = useAuth()
  useEffect(() => { api.get(user?.role === 'Owner' ? '/dashboard/owner' : '/dashboard').then(({ data: payload }) => { console.log('[API] Dashboard loaded'); setData(payload) }).catch((error) => console.error('[ERROR] Dashboard load failed', error)) }, [user?.role])
  if (!data) return <p className="py-10 text-center text-slate-500">Loading your workspace…</p>
  return user?.role === 'Owner' ? <OwnerDashboard data={data} /> : <RoleDashboard data={data} />
}
function RoleDashboard({ data }) { const stats = [{ label: 'Total bugs', value: data.total, trend: 'All workspace issues' }, { label: 'Open work', value: data.open, trend: 'Needs attention' }, { label: 'Resolved', value: data.resolved, trend: 'Resolved issues' }, { label: 'Projects', value: data.projects, trend: `${data.developers} developers` }]; return <div className="grid gap-6"><section className="rounded-lg bg-gradient-to-r from-slate-950 via-slate-900 to-sky-950 p-6 text-white shadow-sm"><p className="text-sm font-bold text-sky-200">Workspace overview</p><h2 className="mt-2 text-3xl font-black">Track. Manage. Resolve.</h2><div className="mt-5 flex gap-3"><Button to="/bugs/new" variant="secondary">Create bug</Button><Button to="/reports" variant="secondary">View reports</Button></div></section><section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat, index) => <StatCard key={stat.label} {...stat} icon={icons[index]} />)}</section><section><div className="mb-4 flex items-center justify-between"><h3 className="text-xl font-black">Recent bugs</h3><Button to="/bugs" variant="ghost">View all</Button></div>{data.recentBugs?.length ? <BugTable bugs={data.recentBugs} /> : <Empty text="No bugs have been reported in this organization." />}</section></div> }
function OwnerDashboard({ data }) { const stats = [{ label: 'Employees', value: data.stats.employees, trend: `${data.stats.activeUsers} active` }, { label: 'Projects', value: data.stats.projects, trend: `${data.stats.teams} teams` }, { label: 'Tasks', value: data.stats.tasks, trend: `${data.stats.requirements} requirements` }, { label: 'Bugs', value: data.stats.bugs, trend: `${data.stats.pendingInvitations} pending invites` }]; return <div className="grid gap-6"><section className="rounded-xl bg-gradient-to-r from-slate-950 via-slate-900 to-indigo-950 p-6 text-white"><p className="text-sm font-bold text-indigo-200">Owner control center</p><h2 className="mt-2 text-3xl font-black">Organization command center</h2><div className="mt-5 flex flex-wrap gap-3"><Button to="/users" variant="secondary">Manage employees</Button><Button to="/teams" variant="secondary">Manage teams</Button><Button to="/settings" variant="secondary">Organization settings</Button></div></section><section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat, index) => <StatCard key={stat.label} {...stat} icon={icons[index]} />)}</section><section className="grid gap-6 xl:grid-cols-2"><Panel title="Team workload">{data.workload.length ? data.workload.map((item) => <div key={item._id || 'unassigned'} className="flex justify-between border-b border-slate-100 py-3 text-sm dark:border-slate-800"><span>{item.name || 'Unassigned'}</span><span>{item.completed}/{item.tasks} completed</span></div>) : <Empty text="No assigned tasks yet." />}</Panel><Panel title="Recent activity">{data.recentActivity.length ? data.recentActivity.map((item) => <div key={item._id} className="border-b border-slate-100 py-3 text-sm dark:border-slate-800"><strong>{item.actor?.name || 'System'}</strong> {item.action}<p className="mt-1 text-xs text-slate-500">{new Date(item.createdAt).toLocaleString()}</p></div>) : <Empty text="No activity recorded yet." />}</Panel><Panel title="Recent uploads">{data.recentUploads.length ? data.recentUploads.map((item) => <a key={item._id} href={item.url} target="_blank" rel="noreferrer" className="block border-b border-slate-100 py-3 text-sm hover:text-indigo-600 dark:border-slate-800">{item.filename} <span className="text-slate-500">by {item.uploadedBy?.name || 'Unknown'}</span></a>) : <Empty text="No recent uploads." />}</Panel><Panel title="Organization growth">{data.growth.length ? data.growth.map((item) => <div key={item._id} className="flex justify-between py-2 text-sm"><span>{item._id}</span><strong>{item.users} new employees</strong></div>) : <Empty text="No employee growth in the past 30 days." />}</Panel></section></div> }
function Panel({ title, children }) { return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 className="text-lg font-black">{title}</h3><div className="mt-3">{children}</div></section> }
function Empty({ text }) { return <p className="rounded-lg border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">{text}</p> }
