import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
const colors = ['#0ea5e9', '#14b8a6', '#f59e0b', '#ef4444', '#8b5cf6', '#64748b']
const chart = (items = []) => items.map((item) => ({ name: item._id || 'Unspecified', value: item.count || item.bugs || 0 }))
export default function AnalyticsCharts({ reports = {} }) {
  const monthly = (reports.monthly || []).map((item) => ({ month: `${item._id.month}/${item._id.year}`, bugs: item.bugs }))
  const status = chart(reports.byStatus); const priority = chart(reports.byPriority)
  return <div className="grid gap-5 xl:grid-cols-3"><ChartCard title="Monthly bug reports" className="xl:col-span-2"><ResponsiveContainer width="100%" height={300}><AreaChart data={monthly}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="month" /><YAxis /><Tooltip /><Area type="monotone" dataKey="bugs" stroke="#0ea5e9" fill="#0ea5e933" /></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Bugs by status"><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={status} dataKey="value" innerRadius={72} outerRadius={108} paddingAngle={4}>{status.map((entry, index) => <Cell key={entry.name} fill={colors[index % colors.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></ChartCard><ChartCard title="Bugs by priority" className="xl:col-span-3"><ResponsiveContainer width="100%" height={260}><BarChart data={priority}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="value" fill="#0f172a" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard></div>
}
function ChartCard({ title, className = '', children }) { return <div className={`rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 ${className}`}><h3 className="mb-4 text-lg font-bold">{title}</h3>{children}</div> }
