import { useCallback, useEffect, useMemo, useState } from 'react'
import { FiCalendar, FiChevronLeft, FiChevronRight } from 'react-icons/fi'
import api from '../../services/api.js'
import { PageHeader } from '../Projects/Projects.jsx'

const views = ['Month', 'Week', 'Day', 'Agenda']
const startDay = (date) => new Date(date.getFullYear(), date.getMonth(), 1).getDay()
const sameDay = (a, b) => a && a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate()

export default function Calendar() {
  const [view, setView] = useState('Month'); const [cursor, setCursor] = useState(new Date()); const [items, setItems] = useState([])
  const load = useCallback(async () => { try { const [tasks, bugs, projects] = await Promise.all([api.get('/tasks'), api.get('/bugs', { params: { limit: 100 } }), api.get('/projects')]); const records = [...tasks.data.filter((task) => task.deadline).map((task) => ({ id: `task-${task._id}`, date: new Date(task.deadline), title: task.title, type: 'Task', color: 'bg-indigo-500', meta: task.assignee?.name || 'Unassigned' })), ...bugs.data.data.filter((bug) => bug.dueDate).map((bug) => ({ id: `bug-${bug._id}`, date: new Date(bug.dueDate), title: bug.title, type: 'Bug', color: 'bg-rose-500', meta: bug.assignedDeveloper?.name || 'Unassigned' })), ...projects.data.flatMap((project) => (project.milestones || []).filter((milestone) => milestone.dueDate).map((milestone, index) => ({ id: `milestone-${project._id}-${index}`, date: new Date(milestone.dueDate), title: milestone.title, type: 'Milestone', color: 'bg-emerald-500', meta: project.name })))]; setItems(records); console.log('[WorkSphere] Calendar loaded', { itemCount: records.length }) } catch (error) { console.error('[WorkSphere] Calendar load failed', error) } }, [])
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer) }, [load])
  const dates = useMemo(() => Array.from({ length: 42 }, (_, index) => new Date(cursor.getFullYear(), cursor.getMonth(), index - startDay(cursor) + 1)), [cursor])
  const title = cursor.toLocaleDateString(undefined, { month: 'long', year: 'numeric' }); const shift = (amount) => setCursor((date) => new Date(date.getFullYear(), date.getMonth() + amount, 1))
  const displayItems = view === 'Agenda' ? [...items].sort((a, b) => a.date - b.date) : items
  return <div className="grid gap-6"><PageHeader title="Calendar" text="Tasks, bugs, deadlines, and milestones across your workspace." /><section className="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><header className="flex flex-col gap-4 border-b border-slate-100 p-4 dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><button onClick={() => shift(-1)} aria-label="Previous month" className="rounded-xl p-2 hover:bg-slate-100 dark:hover:bg-slate-800"><FiChevronLeft /></button><h2 className="min-w-40 text-lg font-black">{title}</h2><button onClick={() => shift(1)} aria-label="Next month" className="rounded-xl p-2 hover:bg-slate-100 dark:hover:bg-slate-800"><FiChevronRight /></button></div><div className="flex rounded-xl bg-slate-100 p-1 dark:bg-slate-800">{views.map((item) => <button key={item} onClick={() => setView(item)} className={`rounded-lg px-3 py-1.5 text-xs font-bold transition ${view === item ? 'bg-white text-indigo-700 shadow-sm dark:bg-slate-950 dark:text-indigo-300' : 'text-slate-500'}`}>{item}</button>)}</div></header>{view === 'Agenda' ? <Agenda items={displayItems} /> : <Month dates={dates} items={items} currentMonth={cursor.getMonth()} compact={view !== 'Month'} />}</section></div>
}
function Month({ dates, items, currentMonth, compact }) { return <div className="overflow-x-auto"><div className="min-w-[720px]"><div className="grid grid-cols-7 border-b border-slate-100 text-center text-xs font-bold uppercase tracking-wide text-slate-400 dark:border-slate-800">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day) => <div key={day} className="p-3">{day}</div>)}</div><div className="grid grid-cols-7">{dates.map((date) => <div key={date.toISOString()} className={`min-h-32 border-b border-r border-slate-100 p-2 dark:border-slate-800 ${date.getMonth() !== currentMonth ? 'bg-slate-50/70 text-slate-400 dark:bg-slate-950/30' : ''}`}><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${sameDay(date, new Date()) ? 'bg-indigo-600 text-white' : ''}`}>{date.getDate()}</span><div className="mt-1 grid gap-1">{items.filter((item) => sameDay(item.date, date)).slice(0, compact ? 1 : 3).map((item) => <div key={item.id} title={item.title} className="flex items-center gap-1 truncate rounded-md bg-slate-100 px-1.5 py-1 text-[11px] font-medium dark:bg-slate-800"><span className={`h-1.5 w-1.5 rounded-full ${item.color}`} />{item.title}</div>)}</div></div>)}</div></div></div> }
function Agenda({ items }) { return <div className="divide-y divide-slate-100 dark:divide-slate-800">{items.length ? items.map((item) => <div key={item.id} className="flex gap-4 p-4"><div className="w-[5.5rem] shrink-0 text-sm font-bold">{item.date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</div><span className={`mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full ${item.color}`} /><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-slate-500">{item.type} · {item.meta}</p></div></div>) : <p className="p-10 text-center text-sm text-slate-500"><FiCalendar className="mx-auto mb-3 h-6 w-6" />No dated work items yet.</p>}</div> }
