import { useCallback, useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { FiUserPlus } from 'react-icons/fi'
import Button from '../../components/Buttons/Button.jsx'
import api from '../../services/api.js'
import { PageHeader } from '../Projects/Projects.jsx'
import { useAuth } from '../../hooks/useAuth.js'

export default function Users() {
  const [users, setUsers] = useState([])
  const [invitations, setInvitations] = useState([]); const [teams, setTeams] = useState([]); const [showInvite, setShowInvite] = useState(false); const [form, setForm] = useState({ role: 'Developer', team: '' }); const { user } = useAuth()
  const load = useCallback(() => { api.get('/users').then(({ data }) => setUsers(data)).catch(() => toast.error('Could not load members')); if (user?.role === 'Owner') { api.get('/organization/invitations').then(({ data }) => setInvitations(data)).catch(() => toast.error('Could not load invitations')); api.get('/teams').then(({ data }) => setTeams(data)).catch(() => {}) } }, [user?.role])
  useEffect(() => { load() }, [load])
  const invite = async (event) => { event.preventDefault(); try { await api.post('/organization/invitations', { ...form, team: form.team || undefined }); toast.success('Invitation email sent'); setShowInvite(false); setForm({ role: 'Developer', team: '' }); load() } catch (error) { toast.error(error.response?.data?.message || 'Could not send invitation') } }
  const action = async (id, type) => { try { if (type === 'cancel') await api.delete(`/organization/invitations/${id}`); else await api.post(`/organization/invitations/${id}/resend`); toast.success(type === 'cancel' ? 'Invitation canceled' : 'Invitation resent'); load() } catch (error) { toast.error(error.response?.data?.message || 'Request failed') } }
  const updateMember = async (id, update) => { try { await api.put(`/users/${id}`, update); toast.success('Employee updated'); load() } catch (error) { toast.error(error.response?.data?.message || 'Could not update employee') } }
  const owner = user?.role === 'Owner'
  return <div className="grid gap-6"><PageHeader title="Users" text="Organization members and their workspace roles." action={owner ? <Button icon={FiUserPlus} onClick={() => setShowInvite(true)}>Invite user</Button> : null} />
    {showInvite && <form onSubmit={invite} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 md:grid-cols-3"><input required type="email" placeholder="Employee email" value={form.email || ''} onChange={(e) => setForm({ ...form, email: e.target.value })} className="rounded-lg border border-slate-300 bg-transparent p-2 dark:border-slate-700"/><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className="rounded-lg border border-slate-300 bg-transparent p-2 dark:border-slate-700">{['Project Manager', 'Team Manager', 'Developer', 'Tester', 'QA Engineer', 'UI Designer', 'DevOps Engineer', 'Viewer'].map((role) => <option key={role}>{role}</option>)}</select><select value={form.team} onChange={(e) => setForm({ ...form, team: e.target.value })} className="rounded-lg border border-slate-300 bg-transparent p-2 dark:border-slate-700"><option value="">No team yet</option>{teams.map((team) => <option key={team._id} value={team._id}>{team.name}</option>)}</select><div className="flex gap-3 md:col-span-3"><Button type="submit">Send invitation</Button><Button type="button" variant="secondary" onClick={() => setShowInvite(false)}>Cancel</Button></div></form>}
    {owner && <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-200 px-4 py-3 dark:border-slate-800"><h3 className="font-bold">Pending invitations</h3><span className="text-sm text-slate-500">{invitations.length} pending</span></div>{invitations.map((item) => <div key={item._id} className="flex flex-wrap items-center gap-3 border-b border-slate-100 px-4 py-3 text-sm dark:border-slate-800"><div className="min-w-48 flex-1"><p className="font-semibold">{item.email}</p><p className="text-slate-500">{item.role} · expires {new Date(item.expiresAt).toLocaleDateString()}</p></div><Button variant="secondary" onClick={() => action(item._id, 'resend')}>Resend</Button><Button variant="secondary" onClick={() => action(item._id, 'cancel')}>Cancel</Button></div>)}{!invitations.length && <p className="p-5 text-sm text-slate-500">No pending invitations.</p>}</section>}
    <div className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><table className="min-w-full divide-y divide-slate-200 text-sm dark:divide-slate-800"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500 dark:bg-slate-950"><tr>{['User', 'Email', 'Role', 'Status', 'Actions'].map((heading) => <th key={heading} className="px-4 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{users.map((member) => <tr key={member._id}><td className="px-4 py-4 font-bold">{member.name}</td><td className="px-4 py-4 text-slate-500">{member.email}</td><td className="px-4 py-4">{owner && member._id !== user.id ? <select value={member.role} onChange={(e) => updateMember(member._id, { role: e.target.value })} className="rounded border border-slate-300 bg-transparent p-1 dark:border-slate-700">{['Project Manager', 'Team Manager', 'Developer', 'Tester', 'QA Engineer', 'UI Designer', 'DevOps Engineer', 'Viewer'].map((role) => <option key={role}>{role}</option>)}</select> : member.role}</td><td className="px-4 py-4">{member.active === false ? 'Disabled' : 'Active'}</td><td className="px-4 py-4">{owner && member._id !== user.id && <div className="flex gap-2"><Button variant="secondary" className="px-2 py-1.5" onClick={() => updateMember(member._id, { active: member.active === false })}>{member.active === false ? 'Enable' : 'Disable'}</Button><Button variant="danger" className="px-2 py-1.5" onClick={() => { if (window.confirm(`Remove ${member.name}?`)) api.delete(`/users/${member._id}`).then(() => { toast.success('Employee removed'); load() }).catch((error) => toast.error(error.response?.data?.message || 'Could not remove employee')) }}>Remove</Button></div>}</td></tr>)}</tbody></table>{!users.length ? <p className="p-10 text-center text-slate-500">No organization members found.</p> : null}</div></div>
}
