import { useCallback, useEffect, useMemo, useState } from 'react'
import toast from 'react-hot-toast'
import { FiCalendar, FiFilter, FiSearch } from 'react-icons/fi'
import api from '../../services/api.js'
import { PageHeader } from '../Projects/Projects.jsx'

const columns = ['Pending', 'Assigned', 'In Progress', 'Under Review', 'Completed', 'Rejected', 'Reopened']
const priorityStyle = { Critical: 'bg-rose-100 text-rose-700 dark:bg-rose-500/15 dark:text-rose-300', High: 'bg-amber-100 text-amber-700 dark:bg-amber-500/15 dark:text-amber-300', Medium: 'bg-sky-100 text-sky-700 dark:bg-sky-500/15 dark:text-sky-300', Low: 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300' }

export default function Kanban() {
  const [tasks, setTasks] = useState([]); const [query, setQuery] = useState(''); const [dragId, setDragId] = useState(null); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { try { console.log('[WorkSphere] Loading Kanban tasks'); const { data } = await api.get('/tasks'); setTasks(data) } catch (error) { console.error('[WorkSphere] Kanban load failed', error); toast.error('Could not load task board') } finally { setLoading(false) } }, [])
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer) }, [load])
  const visible = useMemo(() => tasks.filter((task) => `${task.title} ${task.project?.name || ''} ${task.assignee?.name || ''}`.toLowerCase().includes(query.toLowerCase())), [tasks, query])
  const move = async (status) => {
    const task = tasks.find((item) => item._id === dragId); if (!task || task.status === status) return
    setTasks((items) => items.map((item) => item._id === dragId ? { ...item, status } : item))
    try { await api.put(`/tasks/${dragId}`, { status }); console.log('[WorkSphere] Kanban task moved', { taskId: dragId, status }); toast.success(`Moved to ${status}`) } catch (error) { console.error('[WorkSphere] Kanban move failed', error); toast.error('Could not update task'); load() } finally { setDragId(null) }
  }
  return <div className="grid gap-6"><PageHeader title="Kanban board" text="Move work through your team’s delivery workflow. Changes are saved immediately." /><div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:flex-row sm:items-center"><label className="flex flex-1 items-center gap-2 rounded-xl bg-slate-50 px-3 py-2 dark:bg-slate-950"><FiSearch className="text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Search tasks, projects, or assignees" /></label><span className="flex items-center gap-2 px-2 text-sm text-slate-500"><FiFilter /> {visible.length} tasks</span></div>{loading ? <p className="py-10 text-center text-slate-500">Loading work board…</p> : <div className="kanban-scroll grid gap-4 overflow-x-auto pb-4" style={{ gridTemplateColumns: `repeat(${columns.length}, minmax(275px, 1fr))` }}>{columns.map((status) => <section key={status} onDragOver={(event) => event.preventDefault()} onDrop={() => move(status)} className="min-h-96 rounded-2xl border border-slate-200/80 bg-slate-100/70 p-3 dark:border-slate-800 dark:bg-slate-900/70"><header className="mb-3 flex items-center justify-between px-1"><h2 className="text-sm font-bold">{status}</h2><span className="rounded-full bg-white px-2 py-0.5 text-xs font-bold text-slate-500 shadow-sm dark:bg-slate-800">{visible.filter((task) => task.status === status).length}</span></header><div className="grid gap-3">{visible.filter((task) => task.status === status).map((task) => <article key={task._id} draggable onDragStart={() => setDragId(task._id)} className="cursor-grab rounded-xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md active:cursor-grabbing dark:border-slate-800 dark:bg-slate-950"><div className="flex items-start justify-between gap-2"><p className="font-semibold leading-5">{task.title}</p><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${priorityStyle[task.priority] || priorityStyle.Medium}`}>{task.priority}</span></div><p className="mt-3 text-xs text-slate-500">{task.project?.key || task.project?.name || 'No project'}</p><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>{task.assignee?.name || 'Unassigned'}</span>{task.deadline ? <span className="flex items-center gap-1"><FiCalendar />{new Date(task.deadline).toLocaleDateString()}</span> : null}</div></article>)}{!visible.some((task) => task.status === status) ? <p className="rounded-xl border border-dashed border-slate-300 p-4 text-center text-xs text-slate-500 dark:border-slate-700">Drop a task here</p> : null}</div></section>)}</div>}</div>
}
